set(CMAKE_C_COMPILER "c:/program files/microchip/xc32/v4.40/bin/xc32-gcc.exe")
set(CMAKE_CC_COMPILER "c:/program files/microchip/xc32/v4.40/bin/xc32-g++.exe")
set(MP_CC_DIR "c:/program files/microchip/xc32/v4.40")
set(MP_CPPC_DIR "c:/program files/microchip/xc32/v4.40")
set(MP_AS "c:/program files/microchip/xc32/v4.40/bin/xc32-as.exe")
set(MP_LD "c:/program files/microchip/xc32/v4.40/bin/xc32-ld.exe")
set(MP_AR "c:/program files/microchip/xc32/v4.40/bin/xc32-ar.exe")
set(MP_BIN2HEX "c:/program files/microchip/xc32/v4.40/bin/xc32-bin2hex.exe")
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
